export default {
    "Brighton & Hove Albion": { teamName: "Brighton", sub: "https://www.reddit.com/r/brightonhovealbion" },
    "Newcastle United FC": { teamName: "Newcastle", sub: "https://www.reddit.com/r/NUFC" },
    "Reading": { teamName: "Reading", sub: "http://www.reddit.com/r/Urz" },
    "Leeds United": { teamName: "Leeds", sub: "http://www.reddit.com/r/LeedsUnited" },
    "Huddersfield Town": { teamName: "Huddersfield", sub: "http://www.reddit.com/r/huddersfieldtownfc" },
    "Derby County": { teamName: "Derby", sub: "http://www.reddit.com/r/DerbyCounty" },
    "Sheffield Wednesday": { teamName: "Sheff Wed", sub: "http://www.reddit.com/r/SheffieldWednesday" },
    "Barnsley FC": { teamName: "Barnsley", sub: "https://www.reddit.com/r/BarnsleyFC" },
    "Fulham FC": { teamName: "Fulham", sub: "http://www.reddit.com/r/fulhamfc" },
    "Norwich City FC": { teamName: "Norwich", sub: "https://www.reddit.com/r/NorwichCity" },
    "Preston North End": { teamName: "Preston", sub: "http://www.reddit.com/r/pne" },
    "Birmingham City": { teamName: "Birmingham", sub: "http://www.reddit.com/r/bcfc" },
    "Brentford FC": { teamName: "Brentford", sub: "http://www.reddit.com/r/Brentford" },
    "Aston Villa FC": { teamName: "Aston Villa", sub: "https://www.reddit.com/r/avfc" },
    "Cardiff City FC": { teamName: "Cardiff", sub: "http://www.reddit.com/r/bluebirds" },
    "Wolverhampton Wanderers FC": { teamName: "Wolves", sub: "http://www.reddit.com/r/WWFC" },
    "Ipswich Town": { teamName: "Ipswich Town", sub: "http://www.reddit.com/r/IpswichTownFC" },
    "Queens Park Rangers": { teamName: "QPR", sub: "http://www.reddit.com/r/superhoops" },
    "Nottingham Forest": { teamName: "Nottm Forest", sub: "http://www.reddit.com/r/nffc" },
    "Bristol City": { teamName: "Bristol City", sub: "http://www.reddit.com/r/BristolCity" },
    "Wigan Athletic FC": { teamName: "Wigan", sub: "https://www.reddit.com/r/latics" },
    "Blackburn Rovers FC": { teamName: "Blackburn", sub: "http://www.reddit.com/r/brfc" },
    "Burton Albion FC": { teamName: "Burton", sub: "https://www.reddit.com/r/BurtonAlbion" },
    "Rotherham United": { teamName: "Rotherham", sub: "http://www.reddit.com/r/RotherhamUtd" },
};